import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { read, utils } from 'xlsx';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const XLSX_PATH = join(__dirname, '..', 'public', 'year7_recall_sheets_v3.xlsx');
const OUT_PATH = join(__dirname, '..', 'src', 'data', 'staticData.js');

function parseExcel() {
  if (!existsSync(XLSX_PATH)) {
    console.warn('Excel file not found at', XLSX_PATH, '— writing empty arrays');
    writeFileSync(OUT_PATH, `export const QUESTIONS = [];\nexport const LESSONS = [];\nexport const ROTAS = [];\n`);
    return;
  }

  const buf = readFileSync(XLSX_PATH);
  const wb = read(buf, { type: 'buffer' });

  // Parse questions sheet
  const qSheet = wb.Sheets['questions'] || wb.Sheets[wb.SheetNames.find(n => n.toLowerCase() === 'questions')];
  const lSheet = wb.Sheets['lessons'] || wb.Sheets[wb.SheetNames.find(n => n.toLowerCase() === 'lessons')];
  const rSheet = wb.Sheets['rotas'] || wb.Sheets[wb.SheetNames.find(n => n.toLowerCase() === 'rotas')];

  const rawQuestions = qSheet ? utils.sheet_to_json(qSheet).map(row => ({
    id: String(row['id'] || '').trim(),
    lesson_id: String(row['lesson_id'] || '').trim(),
    topic_id: String(row['topic_id'] || '').trim(),
    topic_name: String(row['topic_name'] || '').trim(),
    lesson_number: row['lesson_number'] !== undefined ? String(row['lesson_number']).trim() : '',
    lesson_title: String(row['lesson_title'] || '').trim(),
    question: String(row['question'] || '').trim(),
    answer: String(row['answer'] || '').trim(),
  })).filter(q => q.id && q.question) : [];

  // Clip to max 4 questions per lesson_id
  const lessonCounts = {};
  const questions = rawQuestions.filter(q => {
    lessonCounts[q.lesson_id] = (lessonCounts[q.lesson_id] || 0) + 1;
    return lessonCounts[q.lesson_id] <= 4;
  });

  const lessons = lSheet ? utils.sheet_to_json(lSheet).map(row => ({
    lesson_id: String(row['lesson_id'] || '').trim(),
    topic_id: String(row['topic_id'] || '').trim(),
    topic_name: String(row['topic_name'] || '').trim(),
    lesson_number: row['lesson_number'] !== undefined ? String(row['lesson_number']).trim() : '',
    lesson_title: String(row['lesson_title'] || '').trim(),
  })).filter(l => l.lesson_id) : [];

  const rotas = rSheet ? utils.sheet_to_json(rSheet).map(row => ({
    rota_id: String(row['rota_id'] || '').trim(),
    rota_name: String(row['rota_name'] || '').trim(),
    lesson_id: String(row['lesson_id'] || '').trim(),
    lesson_order: Number(row['lesson_order']),
  })).filter(r => r.rota_id && r.lesson_id) : [];

  const output = `// Auto-generated by scripts/parseExcel.js — do not edit manually
export const QUESTIONS = ${JSON.stringify(questions, null, 2)};

export const LESSONS = ${JSON.stringify(lessons, null, 2)};

export const ROTAS = ${JSON.stringify(rotas, null, 2)};
`;

  writeFileSync(OUT_PATH, output);
  console.log(`Parsed ${questions.length} questions, ${lessons.length} lessons, ${rotas.length} rota entries`);
}

parseExcel();
